# Configuration file for Cloud Foundry, see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html
applications:
- name: educama-api-gateway
  host: educama-api-gateway
  path: ../../api/target/api-0.0.1-SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack.git#v3.10
  memory: 512M
  disk_quota: 256M
  env:
    EDUCAMA_BACKEND_URL: http://educama-backend.local.pcfdev.io
    EDUCAMA_FLIGHTSERVICE_URL: http://educama-flight-service-sandbox.mybluemix.net          

